spring.application.name=oms-risk-service
server.port=8082

spring.kafka.bootstrap-servers=localhost:9092
spring.kafka.properties.schema.registry.url=http://localhost:8081

#Avro serializer
spring.kafka.producer.key-serializer=org.apache.kafka.common.serialization.StringSerializer
spring.kafka.producer.value-serializer=io.confluent.kafka.serializers.KafkaAvroSerializer

# Avro deserialization
spring.kafka.consumer.key-deserializer=org.apache.kafka.common.serialization.StringDeserializer
spring.kafka.consumer.value-deserializer=io.confluent.kafka.serializers.KafkaAvroDeserializer


management.endpoints.web.exposure.include=health,info,metrics,env,beans,prometheus
management.endpoint.prometheus.enabled=true
management.endpoint.health.show-details=always

# Consumer group ID
spring.kafka.consumer.group-id=oms-risk-service
# Start from beginning if no offset is committed
spring.kafka.consumer.auto-offset-reset=earliest

spring.kafka.consumer.properties.specific.avro.reader=true

